
var AUDIO_CODECS = [			
	{ codec: "mp4a.40", 	description: "MPEG-4 AAC"},
	{ codec: "mp4a.40.1", 	description: "MPEG-4 AAC Main"},
	{ codec: "mp4a.40.2", 	description: "MPEG-4 AAC-LC"},
	{ codec: "mp4a.40.3", 	description: "MPEG-4 AAC-SSR"},
	{ codec: "mp4a.40.4", 	description: "MPEG-4 AAC-LTP"},
	{ codec: "mp4a.40.5", 	description: "MPEG-4 AAC-SBR"},
	{ codec: "mp4a.40.6", 	description: "MPEG-4 AAC-Scalable"},
	{ codec: "mp4a.40.7", 	description: "MPEG-4 TWIN VQ"},
	{ codec: "mp4a.40.8", 	description: "MPEG-4 CELP"},
	{ codec: "mp4a.40.9", 	description: "MPEG-4 HVCX"},
	{ codec: "mp4a.40.12", 	description: "MPEG-4 TTSI"},
	{ codec: "mp4a.40.13", 	description: "MPEG-4 Main Synthetic"},
	{ codec: "mp4a.40.14", 	description: "MPEG-4 Wavetable Synthetis"},
	{ codec: "mp4a.40.15", 	description: "MPEG-4 General Midi"},
	{ codec: "mp4a.40.16", 	description: "MPEG-4 ALGO_SYNTH_AUDIO_FX"},
	{ codec: "mp4a.40.17", 	description: "MPEG-4 ER_AAC_LC"},
	{ codec: "mp4a.40.19", 	description: "MPEG-4 ER_AAC_LTP"},
	{ codec: "mp4a.40.20", 	description: "MPEG-4 ER_AAC_SCALABLE"},
	{ codec: "mp4a.40.21", 	description: "MPEG-4 ER_TWINVQ"},
	{ codec: "mp4a.40.22", 	description: "MPEG-4 ER_BSAC"},
	{ codec: "mp4a.40.23", 	description: "MPEG-4 ER_AAC_LD"},
	{ codec: "mp4a.40.24", 	description: "MPEG-4 ER_CELP"},
	{ codec: "mp4a.40.25", 	description: "MPEG-4 ER_HVXC"},
	{ codec: "mp4a.40.26", 	description: "MPEG-4 ER_HILN"},
	{ codec: "mp4a.40.27", 	description: "MPEG-4 ER_PARAMETRIC"},
	{ codec: "mp4a.40.28", 	description: "MPEG-4 SSC"},
	{ codec: "mp4a.40.29", 	description: "MPEG-4 AAC_PS"},
	{ codec: "mp4a.40.32", 	description: "MPEG-4 LAYER1"},
	{ codec: "mp4a.40.33", 	description: "MPEG-4 LAYER2"},
	{ codec: "mp4a.40.34", 	description: "MPEG-4 LAYER3"},
	{ codec: "mp4a.40.35", 	description: "MPEG-4 DST"},
	{ codec: "mp4a.40.36", 	description: "MPEG-4 ALS"},
	{ codec: "mp4a.66", 	description: "MPEG-2 AAC Main Profile"},
	{ codec: "mp4a.67", 	description: "MPEG-2 AAC Low Complexity Profile"},
	{ codec: "mp4a.68", 	description: "MPEG-2 AAC Scalable Sampling Rate Profile"},
	{ codec: "mp4a.69", 	description: "MPEG-2 Audio Part 3"},
	{ codec: "mp4a.6B", 	description: "MPEG-1 Part 3"},
	{ codec: ".mp3", 	description: "MPEG-1/2 Part 3 - QuickTime File Format"},
	{ codec: "mp3", 	description: "MPEG-1/2 Part 3 - QuickTime File Format"},
];

