var CODECS = [
	{ codec:  "3gvo", description: 	"3GPP Video Orientation", type: "Metadata" },	 
	{ codec:  "a3d1", description: 	"Multiview Video Coding", type: "Video" },
	{ codec:  "a3d2", description: 	"Multiview Video Coding", type: "Video" },
	{ codec:  "a3d3", description: 	"Multiview Video Coding", type: "Video" },
	{ codec:  "a3d4", description: 	"Multiview Video Coding", type: "Video" },
	{ codec:  "a3ds", description: 	"Auro-Cx 3D audio", type: "Audio" },
	{ codec:  "ac-3", description: 	"AC-3 audio", type: "Audio" },
	{ codec:  "ac-4", description: 	"AC-4 audio", type: "Audio" },
	{ codec:  "alac", description: 	"Apple lossless audio codec", type: "Audio" },
	{ codec:  "alaw", description: 	"a-Law", type: "Audio" }, 	
	{ codec:  "av01", description: 	"AV1 video", type: "Video" },
	{ codec:  "avc1", description: 	"Advanced Video Coding", type: "Video" },
	{ codec:  "avc2", description: 	"Advanced Video Coding", type: "Video" }, 
	{ codec:  "avc3", description: 	"Advanced Video Coding", type: "Video" }, 
	{ codec:  "avc4", description: 	"Advanced Video Coding", type: "Video" },
	{ codec:  "avcp", description: 	"Advanced Video Coding Parameters", type: "Video" }, 
	{ codec:  "dra1", description: 	"DRA Audio", type: "Audio" },
	{ codec:  "drac", description: 	"Dirac Video Coder", type: "Video" }, 
	{ codec:  "dts+", description: 	"Enhancement layer for DTS layered audio", type: "Audio" },
	{ codec:  "dts-", description: 	"Dependent base layer for DTS layered audio", type: "Audio" },
	{ codec:  "dtsc", description: 	"DTS Coherent Acoustics audio", type: "Audio" }, 
	{ codec:  "dtse", description: 	"DTS Express low bit rate audio, also known as DTS LBR", type: "Audio" },
	{ codec:  "dtsh", description: 	"DTS-HD High Resolution Audio", type: "Audio" }, 
	{ codec:  "dtsl", description: 	"DTS-HD Master Audio", type: "Audio" },
	{ codec:  "dtsx", description: 	"DTS:X", type: "Audio" }, 
	{ codec:  "dvav", description: 	"AVC-based “Dolby Vision”", type: "Video" }, 
	{ codec:  "dvhe", description: 	"HEVC-based “Dolby Vision”", type: "Video" }, 
	{ codec:  "ec-3", description: 	"Enhanced AC-3 audio", type: "Audio" }, 
	{ codec:  "enca", description: 	"Encrypted/Protected audio", type: "Audio" }, 
	{ codec:  "encf", description: 	"Encrypted/Protected font", type: "Systems" }, 
	{ codec:  "encm", description: 	"Encrypted/Protected metadata stream", type: "Systems"}, 
	{ codec:  "encs", description: 	"Encrypted Systems stream", type: "Systems"}, 
	{ codec:  "enct", description: 	"Encrypted Text", type: "Text" },
	{ codec:  "encv", description: 	"Encrypted/protected video", type: "Video" },
	{ codec:  "fdp ", description: 	"File delivery hints", type:  "Hint" },
	{ codec:  "g719", description: 	"ITU-T Recommendation G.719 (2008)", type: "Audio" },
	{ codec:  "g726", description: 	"ITU-T Recommendation G.726 (1990)", type: "Audio" },
	{ codec:  "hev1", description: 	"High Efficiency Video Coding", type: "Video" },
	{ codec:  "hvc1", description: 	"High Efficiency Video Coding", type: "Video" },
	{ codec:  "hvt1", description: 	"High Efficiency Video Coding", type: "Video" },
	{ codec:  "ixse", description: 	"DVB Track Level Index Track", type: "Metadata" },
	{ codec:  "lhv1", description: 	"Layered High Efficiency Video Coding", type: "Video" },
	{ codec:  "lhe1", description: 	"Layered High Efficiency Video Coding", type: "Video" },
	{ codec:  "lht1", description: 	"Layered High Efficiency Video Coding", type: "Video" },
	{ codec:  "m2ts", description: 	"MPEG-2 transport stream for DMB", type:  "Hint" },
	{ codec:  "m4ae", description: 	"MPEG-4 Audio Enhancement MP4v1", type: "Audio" }, 	
	{ codec:  "m4ae", description: 	"MPEG-4 Audio Enhancement MP4v2", type: "Audio" },
	{ codec:  "mett", description: 	"Text timed metadata that is not XML", type: "Metadata" },
	{ codec:  "metx", description: 	"XML timed metadata", type: "Metadata" },
	{ codec:  "mha1", description: 	"MPEG-H Audio (single stream, uncapsulated)", type: "Audio" },
	{ codec:  "mha2", description: 	"MPEG-H Audio (multi-stream, unencapsulated)", type: "Audio" },
	{ codec:  "mhm1", description: 	"MPEG-H Audio (single stream, MHAS encapsulated)", type: "Audio" },
	{ codec:  "mhm2", description: 	"MPEG-H Audio (multi-stream, MHAS encapsulated)", type: "Audio" },
	{ codec:  "mjp2", description: 	"Motion JPEG 2000", type: "Video" },
	{ codec:  "mlix", description: 	"DVB Movie level index track", type: "Metadata" },
	{ codec:  "mlpa", description: 	"MLP Audio", type: "Audio" },
	{ codec:  "mp4a", description: 	"MPEG-4 Audio", type: "Audio" }, 
	{ codec:  "mp4s", description: 	"MPEG-4 Systems", type: "Systems" },
	{ codec:  "mp4v", description: 	"MPEG-4 Visual", type: "Video" },
	{ codec:  "mvc1", description: 	"Multiview coding", type: "Video" },
	{ codec:  "mvc2", description: 	"Multiview coding", type: "Video" },
	{ codec:  "mvc3", description: 	"Multiview coding", type: "Video" },
	{ codec:  "mvc4", description: 	"Multiview coding", type: "Video" },
	{ codec:  "mvd1", description: 	"Multiview coding", type: "Video" },
	{ codec:  "mvd2", description: 	"Multiview coding", type: "Video" },
	{ codec:  "mvd3", description: 	"Multiview coding", type: "Video" },
	{ codec:  "mvd4", description: 	"Multiview coding", type: "Video" },
	{ codec:  "oksd", description: 	"OMA Keys", type: "Metadata" },
	{ codec:  "Opus", description: 	"Opus audio coding", type: "Audio" },
	{ codec:  "pm2t", description: 	"Protected MPEG-2 Transport", type:  "Hint" },
	{ codec:  "prtp", description: 	"Protected RTP Reception", type:  "Hint" },
	{ codec:  "raw ", description: 	"Uncompressed audio", type: "Audio" },	
	{ codec:  "resv", description: 	"Restricted Video", type: "Video" },
	{ codec:  "rm2t", description: 	"MPEG-2 Transport Reception", type:  "Hint" },
	{ codec:  "rrtp", description: 	"RTP reception", type:  "Hint" },
	{ codec:  "rsrp", description: 	"SRTP Reception", type:  "Hint" },
	{ codec:  "rtmd", description: 	"Real Time Metadata Sample Entry(XAVC Format)", type:  "Systems" },
	{ codec:  "rtp ", description: 	"RTP Hints", type:  "Hint" },
	{ codec:  "s263", description: 	"ITU H.263 video (3GPP format)", type: "Video" },	
	{ codec:  "samr", description: 	"Narrowband AMR voice", type: "Audio" },	
	{ codec:  "sawb", description: 	"Wideband AMR voice", type: "Audio" },	
	{ codec:  "sawp", description: 	"Extended AMR-WB (AMR-WB+)", type: "Audio" },	
	{ codec:  "sevc", description: 	"EVRC Voice", type: "Audio" },
	{ codec:  "sm2t", description: 	"MPEG-2 Transport Server", type:  "Hint" },
	{ codec:  "sqcp", description: 	"13K Voice", type: "Audio" },
	{ codec:  "srtp", description: 	"SRTP Hints", type:  "Hint" },
	{ codec:  "ssmv", description: 	"SMV Voice", type: "Audio" },
	{ codec:  "stpp", description: 	"Subtitles (Timed Text)", type: "Text" },
	{ codec:  "STGS", description: 	"Subtitle Sample Entry (HMMP)", type: "Text" },
	{ codec:  "svc1", description: 	"Scalable Video Coding", type: "Video" }, 
	{ codec:  "svc2", description: 	"Scalable Video Coding", type: "Video" }, 
	{ codec:  "svcM", description: 	"SVC Metadata", type: "Metadata" },
	{ codec:  "tc64", description: 	"64 bit timecode samples", type:  "Timecode" },
	{ codec:  "tmcd", description: 	"32 bit timecode samples", type:  "Timecode" },
	{ codec:  "twos", description: 	"Uncompressed 16-bit audio", type: "Audio" },
	{ codec:  "tx3g", description: 	"Timed Text stream", type: "Text" },
	{ codec:  "ulaw", description: 	"Samples have been compressed using uLaw 2:1.", type: "Audio" },
	{ codec:  "unid", description: 	"Dynamic Range Control (DRC) data", type: "Metadata" },
	{ codec:  "urim", description: 	"Binary timed metadata identified by URI", type: "Metadata" },
	{ codec:  "vc-1", description: 	"SMPTE VC-1", type: "Video" },
	{ codec:  "vp08", description: 	"VP8 video", type: "Video" },
	{ codec:  "vp09", description: 	"VP9 video", type: "Video" },
	{ codec:  "wvtt", description: 	"WebVTT", type: "Text" },
];
